export const tasks = [
  {
    id: 1,
    name: "Washing Dishes",
    description: "Description 1",
    completed: false,
    category: "Work",
    sessions: 1,
  },
  {
    id: 2,
    name: "Playing Valorant",
    description: "Description 2",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
  {
    id: 3,
    name: "Playing  2",
    description: "Description 3",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
  {
    id: 4,
    name: "Washing Dishes",
    description: "Description 1",
    completed: false,
    category: "Work",
    sessions: 1,
  },
  {
    id: 5,
    name: "Playing Valorant",
    description: "Description 2",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
  {
    id: 6,
    name: "Playing  2",
    description: "Description 3",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
  {
    id: 1,
    name: "Washing Dishes",
    description: "Description 1",
    completed: false,
    category: "Work",
    sessions: 1,
  },
  {
    id: 2,
    name: "Playing Valorant",
    description: "Description 2",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
  {
    id: 3,
    name: "Playing  2",
    description: "Description 3",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
  {
    id: 4,
    name: "Washing Dishes",
    description: "Description 1",
    completed: false,
    category: "Work",
    sessions: 1,
  },
  {
    id: 5,
    name: "Playing Valorant",
    description: "Description 2",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
  {
    id: 6,
    name: "Playing  2",
    description: "Description 3",
    completed: false,
    category: "Gaming",
    sessions: 1,
  },
];
